apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
    
        root /usr/share/nginx/html;

        client_max_body_size 20M;
        fastcgi_buffers 16 16k; 
        fastcgi_buffer_size 32k;

        location / {
    
            fastcgi_pass 127.0.0.1:9000;
    
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_param SCRIPT_NAME     /index.php;
            fastcgi_param DOCUMENT_ROOT   /var/www/html/public;
    
            fastcgi_param QUERY_STRING    $query_string;
            fastcgi_param REQUEST_METHOD  $request_method;
            fastcgi_param CONTENT_TYPE    $content_type;
            fastcgi_param CONTENT_LENGTH  $content_length;
    
            fastcgi_param REQUEST_URI     $request_uri;
            fastcgi_param DOCUMENT_URI    $document_uri;
            fastcgi_param SERVER_PROTOCOL $server_protocol;
    
            fastcgi_param GATEWAY_INTERFACE CGI/1.1;
            fastcgi_param SERVER_SOFTWARE   nginx/$nginx_version;
    
            fastcgi_param REMOTE_ADDR     $remote_addr;
            fastcgi_param REMOTE_PORT     $remote_port;
            fastcgi_param SERVER_ADDR     $server_addr;
            fastcgi_param SERVER_PORT     $server_port;
            fastcgi_param SERVER_NAME     $server_name;
    
            fastcgi_param HTTPS           $https if_not_empty;
        }
    }