apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-proxy
  template:
    metadata:
      labels:
        app: symfony-proxy
    spec:
      containers:
        - name: php
          image: username/symfony-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: "prod"
            - name: APP_SECRET
              value: "changeme_in_production"
            - name: APP_DEBUG
              value: "0"

            - name: DEFAULT_URI
              value: "http://localhost"

            - name: PROXY_TARGETS
              value: "https://www.php.net,https://symfony.com,https://github.com/,https://uk.wikipedia.org"
            - name: PROXY_DEFAULT_TARGET
              value: "https://uk.wikipedia.org"
            - name: PROXY_TARGET_DOMAINS
              value: "github.com,github.blog"
            - name: PROXY_MAIN_DOMAINS
              value: "github.com,github.blog"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-vol
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"

      volumes:
        - name: nginx-config-vol
          configMap:
            name: nginx-config